apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: My Demo MicroService
  description: API for doing something amazing :)
spec:
  type: openapi
  lifecycle: production
  owner: team-a
  definition:
    $text: https://github.com/APIs-guru/openapi-directory/blob/main/APIs/archive.org/search/1.0.0/openapi.yaml
